services:
  mongo:
    image: mongo:latest
    volumes:
      - f1_sp:/data/db
    ports:
      - "27017:27017"
    networks:
      - back-tier

  server:
    build: ./backend
    ports:
      - "8081:8081"
    # env_file:
    #   - .compose.env
    depends_on:
      - mongo
    networks:
      - front-tier
      - back-tier

  app:
    build: ./frontend
    ports:
      - "8080:8080"
    depends_on:
      - server
    networks:
      - front-tier

volumes:
  f1_sp:
    driver: local

networks:
  front-tier:
  back-tier:
