name: Docker Deploy CI

on:
  push:
    branches: [master]

jobs:
  build-backend-image:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend

    steps:
      - uses: actions/checkout@v3.5.3
        name: Check out code

      - uses: Saionaro/extract-package-version@v1.2.1
        name: Extract version
        id: extract_version
        with:
          path: ./backend

      - uses: mr-smithers-excellent/docker-build-push@v6.2
        name: Build & Push backend docker image
        with:
          image: deepacks/f1squadpro-backend
          tags: ${{ steps.extract_version.outputs.version }}, latest
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

  build-frontend-image:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend

    steps:
      - uses: actions/checkout@v3.5.3
        name: Check out code

      - uses: Saionaro/extract-package-version@v1.2.1
        name: Extract version
        id: extract_version
        with:
          path: ./frontend

      - uses: mr-smithers-excellent/docker-build-push@v6.2
        name: Build & Push frontend docker image
        with:
          image: deepacks/f1squadpro-frontend
          tags: ${{ steps.extract_version.outputs.version }}, latest
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
#   update-backend-service:
#     runs-on: ubuntu-latest
#     needs: [build-backend-image]

#     steps:
#       - name: SSH update backend service
#         uses: appleboy/ssh-action@v0.1.10
#         with:
#           host: ${{ secrets.HOST }}
#           username: ${{ secrets.USERNAME }}
#           key: ${{ secrets.KEY }}
#           passphrase: ${{ secrets.PASSPHRASE }}
#           script: |
#             docker image pull deepacks/f1squadpro-backend:latest
#             docker service update --with-registry-auth --image deepacks/f1squadpro-backend:latest f1_f1-backend
#             docker container prune -f
#             docker image prune -f

